### ISSUE TITLE
applescript error

### ISSUE THREAD

**Issue by Hackmodford** [octo-technology/Xcode-formatter#3]
I've opened the workflow in automator to see if I could get a detailed message as to why it was failing.

Xcode got an error: find: /Users/hackmodford/Dropbox/xCode/MA: No such file or directory
find: Mobile/MA: No such file or directory
find: Mobile.xcodeproj: No such file or directory

The problem is is that my app directory is "MA Mobile" apparently it's looking for "MA" & "Mobile" as two seperate entities. Any way to fix this?

**Comment by Hackmodford** [comment]
So I changed my project to MA-Mobile instead of "MA Mobile" and that fixed it. But if someone else has a project name with a space they will get the same error. FYI

**Comment by Hackmodford** [comment]
Now that I have that problem fixed I'm getting a different error.

Run Applescript failed - 1 error
     //

I'm not sure what "//" means. I was able to run the script on my app delegates .m file but it seems like any other .m file gives this error.

**Comment by mwalbrou** [comment]
Hi Hackmodford ! 

The space issue is now corrected !

For your second error, I advise you to launch the service from automator app, and debug with the macosx console or "display dialog" method in applescript. 

For example, to display files to be formatted : 

```
...
set currentDocument to source document [n]
set currentDocumentPath to path of currentDocument

display dialog currentDocumentPath

set suffix to text ((offset of "." in currentDocumentPath) + 1) thru -1 of currentDocumentPath
...
```

It is the quickest way I found to debug the script for now (just discovered applescript). 

Thank you to keep me informed of what you find !

**Comment by Hackmodford** [comment]
Name with space bug is fixed... now I'm going to attempt to debug the other part

**Comment by Hackmodford** [comment]
I added that line you suggested and it had the correct path... must be later down the line then...

**Comment by Hackmodford** [comment]
the problem is in the

```
set formattedSource to do shell script...

```

I'm thinking it is an actual problem with uncrustify at this point. Any ideas how to check that?

**Comment by mwalbrou** [comment]
Yes : 

1) Try the formatAllSources.sh script. If it works, uncrustify is correctly installed.

2) In the automator script, check that "uncrustifyConfigFilePath" is correctly setted before formatting the files (after the 'tell finder' block)

3) Look at the macosx console during automator script execution : the uncrustify error should be printed

**Comment by Hackmodford** [comment]
K ill take a look tomorrow...

**Comment by mwalbrou** [comment]
Ok, I just updated the workflow to add some poka-yoke to check uncrustify installation and configuration file integrity. 
I also managed to get any other script errors displayed in a pop-up instead of the default fool message "Run Applescript failed - 1 error".

It should be easier for you now ! ;)

Regards.

**Comment by Hackmodford** [comment]
Okay... I just updated the files and tried again. Now when I run it it brings up a dialog that says "Unknown error : //"

the // was just the first line of my code. After "Unknown error :" it spits out the rest of my code in the dialog. It looks like it is the updated/fixed code that uncrustify should return.

**Comment by mwalbrou** [comment]
Okay, this is the first time I face this situation :s.

What version of macosx & Xcode do you use ? 

Did you try the formatAllSources.sh script ? Do you have the same issue ?

**Comment by Hackmodford** [comment]
I had a hunch that it might be related to apple's new literals.

```
self.myArray = @[1,2,3,4];
```

I commented the lines of code in one of my files and it ran perfectly. Then I uncommented it and it worked fine.

Does this mean that uncrustify just doesn't know how to handle this new convention?

**Comment by mwalbrou** [comment]
I am glad you found the solution (and that it is not an appelscript issue ;) ) !

Maybe there is a solution by updating the uncrustify configuration file. I took a look but did not found a solution for now (maybe we have to wait for a new version of uncrustify). 

Let me know if you find one ! I will update the README to add this limitation.

EDIT: Do you agree to close your issue (as it is an uncrustify limitation) ? I opened [an issue](https://github.com/bengardner/uncrustify/issues/104) for this on uncrustify's github page.

**Comment by Hackmodford** [comment]
Yes I do agree.
