### ISSUE TITLE
Is it possible to have an option not to include CodeFormatter directory in the project?

### ISSUE THREAD

**Issue by luosky** [octo-technology/Xcode-formatter#4]
Thank you for this great tool. This is the feature I have been missing so much from Eclipse.

It works great. If we could have an option not to put the CodeFormatter directory in the project, but have a global format setting , that would be even better.

**Comment by luosky** [comment]
I know having a common config file with people working on the same project is good. But having a global personal config is also a common use-case. 

If we can have a global config and a project wide config, just like global git ignore file and project ignore file, that would be really convenient.

**Comment by mwalbrou** [comment]
Hello Iuosky!

It is done! You can update your .workflow file and remove CodeFormatter directory. If the config file is not present in Xcode project's directory, the file located in ~/.uncrustify/ will be used. 

See FAQ in readme file for details!

Regards

(do not forget to close this issue if the correction fits ;))

**Comment by luosky** [comment]
It works wonderful!
