### ISSUE TITLE
Script doesn't work if file path contains dot symbol (.)

### ISSUE THREAD

**Issue by kulynyak** [octo-technology/Xcode-formatter#6]
Script doesn't work if file path contains dot symbol (.) e.g.: _/home/user/xxx/my.project/somefile.h_

Would you mind to replace in _Uncrustify_opened_Xcode_sources.workflow_
line:
`set suffix to text ((offset of "." in currentDocumentPath) + 1) thru -1 of currentDocumentPath`

with:
`set suffix to text (length of currentDocumentPath) thru -1 of currentDocumentPath`
(here is used fact that suffix is tested with 'h', or 'm' and their length is equal to 1 and the fact that file extension is the last part of path string)

I like your project :) Thanks.

**Comment by mwalbrou** [comment]
Hi!
I made the correction, thanks for improvement! ;)
